[DATASTD-1441] ProviderCategory descriptors should be aligned with Ed-Fi standard practice and defined
Ed-Fi-Alliance-OSS/Ed-Fi-Standard pull request #38
Opened 2021-08-09 18:37 UTC by ggaronzik

2021-08-09 19:12 UTC, blmeyers requested changes
Value changes look fine, but formatting seems to have gotten off.

2021-08-09 19:12 UTC, blmeyers commented on Descriptors/ProviderCategoryDescriptor.xml
> +   <ProviderCategoryDescriptor>
```suggestion
	<ProviderCategoryDescriptor>
```

2021-08-09 19:46 UTC, ggaronzik commented on Descriptors/ProviderCategoryDescriptor.xml
> +   <ProviderCategoryDescriptor>
formatting fixed!

2021-08-09 19:48 UTC, blmeyers approved these changes

2021-08-13 17:29 UTC, ejansson requested changes
Other should be added as a new category and Not applicable marked as deprecated.

2021-08-13 17:43 UTC, ggaronzik commented on Descriptors/ProviderCategoryDescriptor.xml
> +		<CodeValue>Other</CodeValue>
@ejansson here is where Other is added as a new ProviderCategory.

2021-08-13 17:44 UTC, ggaronzik commented on Descriptors/ProviderCategoryDescriptor.xml
> +		<Description>DEPRECATED: Not Applicable</Description>
@ejansson here is where Not Applicable is deprecated.

2021-08-13 17:45 UTC, ggaronzik commented
> Other should be added as a new category and Not applicable marked as deprecated.

@ejansson I believe these are covered. I tagged you in a comment for each. Let me know if there are other changes needed.

2021-08-13 17:59 UTC, ejansson approved these changes

2021-08-13 17:59 UTC, merged